wallpaper {
  monitor = DP-1
  path = /home/coosper/Pictures/Wallpaper/VesselCatppuccinWallpaper.png
}

wallpaper {
  monitor = DP-2
  path = /home/coosper/Pictures/Wallpaper/PapaCatppuccinWallpaper.png
}

splash = false