# ═════════════════════════════════════ #
#       COOSPER'S HYPRLAND.CONF         #
# ═════════════════════════════════════ #

# I just need this shit somewhat organised man...

# ═════════════════════════════════════ #
#                COLORS                 #
# ═════════════════════════════════════ #

source=~/.config/hypr/colors.conf

# ═════════════════════════════════════ #
#               MONITORS                #
# ═════════════════════════════════════ #

source=~/.config/hypr/monitors.conf

# ═════════════════════════════════════ #
#               PROGRAMS                #
# ═════════════════════════════════════ #

source=~/.config/hypr/programs.conf

# ═════════════════════════════════════ #
#               AUTOSTART               #
# ═════════════════════════════════════ #

source=~/.config/hypr/autostart.conf

# ═════════════════════════════════════ #
#         ENVIRONMENT VARIABLES         #
# ═════════════════════════════════════ #

source=~/.config/hypr/env.conf

# ═════════════════════════════════════ #
#              PERMISSIONS              #
# ═════════════════════════════════════ #

source=~/.config/hypr/permissions.conf

# ═════════════════════════════════════ #
#              LOOK & FEEL              #
# ═════════════════════════════════════ #

source=~/.config/hypr/look_and_feel.conf

# ═════════════════════════════════════ #
#                 INPUT                 #
# ═════════════════════════════════════ #

source=~/.config/hypr/input.conf

# ═════════════════════════════════════ #
#              KEYBINDINGS              #
# ═════════════════════════════════════ #

source=~/.config/hypr/keybinds.conf

# ═════════════════════════════════════ #
#        WINDOWS & WORKSPACES           #
# ═════════════════════════════════════ #

source=~/.config/hypr/windows_workspaces.conf

# ═════════════════════════════════════ #
#                SWAYOSD                #
# ═════════════════════════════════════ #

source=~/.config/hypr/swayosd.conf
