# ═════════════════════════════════════ #
#              LOOK & FEEL              #
# ═════════════════════════════════════ #
# Borders, gaps, shadows, animations
general {
    gaps_in  = 8
    gaps_out = 10
    border_size = 5
    col.active_border   = $sapphire $mauve 45deg
    col.inactive_border = rgba(495068aa)
    resize_on_border = true
    allow_tearing    = false
    layout           = dwindle
}
decoration {
    rounding = 0
    active_opacity   = 1.0
    inactive_opacity = 0.9
    dim_inactive  = true
    dim_strength  = 0.15
    shadow {
        enabled         = true
        range           = 4
        render_power    = 3
        color           = rgba($crustAlphaee)
        ignore_window   = true
        color_inactive  = rgba($crustAlpha99)
    }
    blur {
        enabled           = true
        size              = 3
        passes            = 2
        new_optimizations = true
        noise             = 0.02
        ignore_opacity    = true
        popups            = true
        vibrancy          = 0.16
    }
}
animations {
    enabled = 1

    bezier = snap,     0.16, 1,    0.3,  1
    bezier = flee,     0.4,  0,    1,    1
    bezier = cruise,   0.25, 1,    0.5,  1
    bezier = material, 0.2,  0,    0,    1
    bezier = spring,   0.18, 1.25, 0.4,  1
    bezier = weight,   0.0,  0.9,  0.1,  1

    animation = windowsIn,   1, 5, snap,   slide
    animation = windowsOut,  1, 4, flee,   slide
    animation = windowsMove, 1, 5, cruise, slide

    animation = fadeIn,     1, 4, material
    animation = fadeOut,    1, 3, flee
    animation = fadeDim,    1, 6, material
    animation = fadeSwitch, 1, 4, material
    animation = fadeShadow, 1, 4, material

    animation = workspaces,       1, 6, weight, slidefade 15%
    animation = specialWorkspace, 1, 5, spring, slidefade 15%

    animation = layersIn,      1, 4, spring,   slide
    animation = layersOut,     1, 3, flee,     slide
    animation = fadeLayersIn,  1, 3, material
    animation = fadeLayersOut, 1, 4, material

    animation = border, 1, 8, material
}
dwindle {
    pseudotile     = true
    preserve_split = true
}
master {
    new_status = master
}
misc {
    force_default_wallpaper = false
    disable_hyprland_logo   = true
}
xwayland {
    force_zero_scaling = true
}