# Volume controls

bind = , XF86AudioRaiseVolume, exec, swayosd-client --monitor eDP-1 --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --monitor eDP-1 --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --monitor eDP-1 --output-volume mute-toggle
bind = , XF86AudioMicMute, exec, swayosd-client --monitor eDP-1 --input-volume mute-toggle

# Brightness controls

bind = , XF86MonBrightnessUp, exec, swayosd-client --monitor eDP-1 --brightness raise
bind = , XF86MonBrightnessDown, exec, swayosd-client --monitor eDP-1 --brightness lower

# Caps lock indicator
bind = , Caps_Lock, exec, --release swayosd-client --monitor eDP-1 --caps-lock

# Media controls

bind = , XF86AudioPlay, exec, swayosd-client --monitor eDP-1 --playerctl play-pause
bind = , XF86AudioNext, exec, swayosd-client --monitor eDP-1 --playerctl next
bind = , XF86AudioPrev, exec, swayosd-client --monitor eDP-1 --playerctl previous
